name: Build

on:
  workflow_call:

jobs:
  build:
    name: 'Build application'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['22.x']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node }}
      - uses: ./.github/actions/setup-pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Pass eslint
        run: npm run lint
      - name: Pass tests of the application
        run: npm run tests
